### ISSUE TITLE
caman.revert(false) - image flickers

### ISSUE THREAD

**Issue by oskarwrobel** [meltingice/CamanJS#130]
Hello,

What I'm doing/is wrong?
I have the same code and image as in your example (http://camanjs.com/examples/), but in my example image flickers each time i call caman.revert(false). In yours everything works perfect :)

My version - https://dl.dropboxusercontent.com/u/6947482/web/caman-test/index.html

**Comment by skyfox93** [comment]
The CDN version is still 4.0.0
