### ISSUE TITLE
Run Camanjs on a new Image() or image data

### ISSUE THREAD

**Issue by michaud** [meltingice/CamanJS#24]
I'm working on an app where i capture the image from my webcam with WebRTC. But it looks like, just from code analysis, that it doesn't support working on a new Image() or image data, is that correct? If so it would be nice to have that, if not how would that work?

**Comment by avandecreme** [comment]
Here is the workaround I found:

```javascript
var image = new Image();
image.onload = function () {
    var div = document.createElement("div");
    div.appendChild(image);
    Caman(image, function () {
        this.sepia(50); // Whatever modification you need to do.
        this.render(function () {
            image = div.childNodes[0];
        });
    });
};
image.src = "image.jpeg";
```

**Comment by RomainMazB** [comment]
@avandecreme > Thanks a lot for this simple ticks.

It's working perfectly. For those who need it, see [my fiddle](https://jsfiddle.net/RomainMazB/frw5a29j/) which:
- Create a simple canvas with green dummy text.
- Rotate this canvas to set it feet in the air and head on the ground 🎸🤘🎵 Pixies🎵🤘🎸
- Download final reversed file
All of this without ever render the canvas in the DOM.
