### ISSUE TITLE
caman on phonegap HiDpi issue

### ISSUE THREAD

**Issue by csteinbacher** [meltingice/CamanJS#80]
If you have an inline property on the canvas element that sets the size, for instance
`<canvas id="something" height="400" width="400"></canvas>`

And you run it in PhoneGap on iOS, it will detect a high res screen, but render the canvas incorrectly and causes the canvas to display nothing it all, it tries to set the size differently from its inline sizing. 

If you are having issues with the canvas displaying nothing after a render, set a data attribute to data-caman-hidpi-disabled="true"

no so much of a bug as a gotcha, but it took me a few hours to figure out.

**Comment by Montrazul** [comment]
We have the 2015. I downloaded the latest version and this is not fixed.
